# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgsdTdoWRN6WOsyuqzMb4dNfWpcrBI6e
"""

import numpy as np

Q=np.array([
    [5,1,2],
    [1,1,3],
    [0,2,5]
])
K=np.array([
    [1,2,3],
    [1,0,2],
    [1,0,1]
])
V=np.array([
    [4,5,6],
    [1,2,3],
    [5,4,5]
])

def attention(Q,K,V):
  d_K=K.shape[-1]
  sim=np.dot(Q,K.T)/np.sqrt(d_K)

  return sim

def softmax(x):
  x=x-np.max(x,axis=-1,keepdims=True)
  exp_x=np.exp(x)
  return exp_x/np.sum(exp_x,axis=-1,keepdims=True)

attention_score=attention(Q,K,V)
attention_weight=softmax(attention_score)
output=attention_weight @ V
print('Attention score:\n',attention_score)
print("Attention weight\n:",attention_weight)
print("Attention output\n:",output)