# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgsdTdoWRN6WOsyuqzMb4dNfWpcrBI6e
"""

import numpy as np

seq_length=5
d_model=8
PE = positional_encoding(seq_length, d_model)

print("Positional Encoding:")
print(PE)

print(PE[0])
print(PE[1])
print(PE[2])

import matplotlib.pyplot as plt

plt.imshow(PE)
plt.xlabel("Embedding Dimension")
plt.ylabel("Position")
plt.title("Positional Encoding")
plt.show()